name: move
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^5.0.3
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^9.0.0
  toast: ^0.1.5
  cupertino_icons: ^0.1.3
  flutter_blue: ^0.8.0
  flame: 1.0.0-rc9
  google_fonts: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - sprite.png
    - squat_1.png
    - squat_2.png
    - squat_3.gif
    - shoulder.png
    - background.png
    - jumping_1.png
    - jumping_2.png
    - jumping_3.png
    - jumping_4.png
    - jumping_5.png
    - correct.png
    - wrong.png
    - skip.png
    - next.png
    - start.png
    - 1.png
    - 2.png
    - 3.png
    - 4.png
    - 5.png
    - moveButton.png
    - connect.png
    - logo.png
    - boxButton.png
    - dinoButton.png
    - dinoExit.png
    - gameButton.png
    - hwButton.png
    - reabButton.png
    - jumpingButton.png
    - crossButton.png
    - squatButton.png
    - cross_1.png
    - cross_2.png
    - snap.png
    - finish.png
    - logo.png
    - exit.png
    - restart.png
    - start_1.png
    - start_2.png
    - start_3.png
    - start_start.png
    - dinoExit.png
    - dino_j.png
    - dino_n.png
    - boxing_back.png
    - punch.png
    - uppercut.png
    - bridge.png
    - crunch.png
    - dumbbell.png
    - plank.png
    - pushUp.png
    - fishing.png
    - tutorial1_background.png
    - tutorial2_background.png
    - ok.png
    - jumping.gif
    - cross.gif
    - num1.png
    - num2.png
    - num3.png
    - num4.png
    - num5.png
    - boxing_clear.png
    - cloud.png
    - cloud1.png
    - cloud2.png
    - sun.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages